### ISSUE TITLE
When modifying a setting for student PIN , reset the app by returning to the map

### ISSUE THREAD

**Issue by kgary** [aayushi195/ReachAPI#76]
After switching PIN settings, the app returned to teh island I was on, but now I am a new student with new state so I should return to the homepage (map) and basically "reset"

**Comment by kgary** [comment]
And when it did reset the map when I went back to it the hero went to island 1 but the clouds were still of islands 1-4

**Comment by AbhishekParmar81** [comment]
![image (2)](https://user-images.githubusercontent.com/35242470/56697428-6ca58500-66a3-11e9-9de7-3fc8c6f320cb.png)
![Screenshot_20190424-150146](https://user-images.githubusercontent.com/35242470/56697429-6d3e1b80-66a3-11e9-8ee8-f0669d3a2f19.png)

**Comment by Bala000** [comment]
https://github.com/aayushi195/ReachAPI/issues/84
When modifying a setting for student PIN from the homelanding page, reset the clouds, avatar, and the app

**Comment by Bala000** [comment]
This has been resolved by maintaining activity state and clearing previous activity in call stack based on if student pin is changed or not.
