### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by kgary** [aayushi195/ReachAPI#78]
App crashes at different points, including returning to the map from a module and tapping on the trasure chest. Not repeatable at this point

**Comment by aayushi195** [comment]
The APP logs when an activity crashes. 
There are no logs on the API side (tomcat server logs)
<img width="1440" alt="Screen Shot 2019-04-24 at 14 47 24" src="https://user-images.githubusercontent.com/18596734/56696686-6a422b80-66a1-11e9-99d6-424a9ca09c44.png">

**Comment by ShipraDEVP** [comment]
Crash cause - The custom DialogFragment (i.e. DialogBuilder) used to enter pin to open Settings page on HomeLoading Page. 
Reason Could be - The Parent fragment (of DialogBuilder HomeLanding) was not getting dismissed before the DialogBuilder was being used in other Activities.
Resolution - created AlertDailog box in place of using the existing custom dialog fragment.
