### ISSUE TITLE
Belt on Module One Avatar in Rewards overlaps with the mouth of blob

### ISSUE THREAD

**Issue by mahima95** [aayushi195/ReachAPI#83]

**Comment by mahima95** [comment]
<img width="257" alt="Screen Shot 2019-04-24 at 10 48 14 AM" src="https://user-images.githubusercontent.com/17384162/56697913-f6098700-66a4-11e9-97bf-b2d17584ee5b.png">

**Comment by mahima95** [comment]
Should we put belt below instead of on the blob? Or This image looks okay?


<img width="257" alt="Screen Shot 2019-04-24 at 10 48 14 AM" src="https://user-images.githubusercontent.com/17384162/56698027-5a2c4b00-66a5-11e9-89be-4106d0ada55c.png">



<img width="256" alt="Screen Shot 2019-04-24 at 3 29 35 PM" src="https://user-images.githubusercontent.com/17384162/56698156-d32ba280-66a5-11e9-8cfb-4eebe0261cda.png">

**Comment by mahima95** [comment]
![Screenshot_1556144733](https://user-images.githubusercontent.com/17384162/56698058-821bae80-66a5-11e9-8f81-b7939d869823.png)

**Comment by aayushi195** [comment]
We would place the belt under the blob (first avatar).
